import Head from "next/head";
import { useState } from "react";

import { motion } from "framer-motion";
import "css.gg/icons/css/close.css";

export default function Home() {
  const [input, setInput] = useState("");
  const [todos, setTodos] = useState<
    Array<{
      name: string;
      done: boolean;
    }>
  >([]);

  const inputHandle = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);
  };
  const clickHandle = () => {
    if (input == "") {
      alert("Ne yapacağına karar ver.");
    }
    // Eğer öyle bir todo varsa hata göster
    else if (todos.find((todo) => todo.name == input)) {
      alert("Bu todo zaten var.");
    } else {
      const newTodo = {
        name: input,
        done: false,
      };
      setTodos([...todos, newTodo]);
      setInput("");
    }
  };

  const removeTodo = (todokey: number) => {
    setTodos(todos.filter((todo, key) => key !== todokey));
  };

  const toggleTodo = (todoKey: number) => {
    setTodos(
      todos.map((todo, key) => {
        if (key == todoKey) {
          todo.done = !todo.done;
        }
        return todo;
      })
    );
  };

  return (
    <>
      <Head>
        <title>YapLenEK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-full flex justify-center">
        <div className="m-16 flex flex-col items-center w-80 bg-white rounded-md shadow-lg overflow-hidden">
          <div className="flex items-center justify-center">
            <form
              className="w-48 flex items-center justify-center flex-col"
              onSubmit={(e) => e.preventDefault()}
            >
              <motion.input
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.8 }}
                className="border-2 rounded-xl p-2 hover:border-gray-700 transition-all duration-100 hover:placeholder:text-gray-700"
                value={input}
                onChange={inputHandle}
                type="text"
                placeholder="Ne yapacaksın len?"
              />
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.8 }}
                className="w-full rounded-xl text-white p-1 m-2 bg-gray-700 hover:bg-gray-600"
                onClick={clickHandle}
              >
                Ekle
              </motion.button>
            </form>
          </div>
          <hr className="w-4/5 border-b border-gray-400 my-2" />
          <ul className="w-4/5 z-50 overflow-y-auto overflow-x-hidden">
            {todos.map((todo, key) => {
              return (
                <motion.div
                  whileHover={{ scale: [1, 1.05, 1] }}
                  //whileTap={{ scale: 0.8 }}
                  className="flex justify-between my-1"
                  key={key}
                >
                  <motion.li
                    whileTap={{ scale: 0.8 }}
                    className={
                      "select-none w-full" + (todo.done ? " line-through" : "")
                    }
                    onClick={() => toggleTodo(key)}
                  >
                    {todo.name}
                  </motion.li>
                  <button className="" onClick={() => removeTodo(key)}>
                    <i className="gg-close"></i>
                  </button>
                </motion.div>
              );
            })}
          </ul>
        </div>
      </main>
    </>
  );
}
